grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/ceramicraft-order-mservice.log

mysql:
  host: "mysql-container" # 127.0.0.1 mysql-container
  port: "3306"
  userName: "root"
  dbName: "order_db"

commodityClient:
  host: "ceramicraft-commodity-mservice"
  port: 5001

paymentClient:
  host: "ceramicraft-payment-mservice"
  port: 5001

kafka:
  host: "kafka-container"
  port: 9092

redis:
  host: "redis-container"
  port: 6379

auditClient:
  host: "localhost"
  port: 50051