// Code generated by MockGen. DO NOT EDIT.
// Source: ./dao/order_product_dao.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/sw5005-sus/ceramicraft-order-mservice/server/repository/model"
)

// MockOrderProductDao is a mock of OrderProductDao interface.
type MockOrderProductDao struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProductDaoMockRecorder
}

// MockOrderProductDaoMockRecorder is the mock recorder for MockOrderProductDao.
type MockOrderProductDaoMockRecorder struct {
	mock *MockOrderProductDao
}

// NewMockOrderProductDao creates a new mock instance.
func NewMockOrderProductDao(ctrl *gomock.Controller) *MockOrderProductDao {
	mock := &MockOrderProductDao{ctrl: ctrl}
	mock.recorder = &MockOrderProductDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProductDao) EXPECT() *MockOrderProductDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderProductDao) Create(ctx context.Context, orderProduct *model.OrderProduct) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, orderProduct)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderProductDaoMockRecorder) Create(ctx, orderProduct interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderProductDao)(nil).Create), ctx, orderProduct)
}

// CreateBatch mocks base method.
func (m *MockOrderProductDao) CreateBatch(ctx context.Context, products []model.OrderProduct) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, products)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockOrderProductDaoMockRecorder) CreateBatch(ctx, products interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockOrderProductDao)(nil).CreateBatch), ctx, products)
}

// GetByOrderNo mocks base method.
func (m *MockOrderProductDao) GetByOrderNo(ctx context.Context, orderNo string) ([]*model.OrderProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderNo", ctx, orderNo)
	ret0, _ := ret[0].([]*model.OrderProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderNo indicates an expected call of GetByOrderNo.
func (mr *MockOrderProductDaoMockRecorder) GetByOrderNo(ctx, orderNo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderNo", reflect.TypeOf((*MockOrderProductDao)(nil).GetByOrderNo), ctx, orderNo)
}
