// Code generated by MockGen. DO NOT EDIT.
// Source: push_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPushClient is a mock of IPushClient interface.
type MockIPushClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPushClientMockRecorder
}

// MockIPushClientMockRecorder is the mock recorder for MockIPushClient.
type MockIPushClientMockRecorder struct {
	mock *MockIPushClient
}

// NewMockIPushClient creates a new mock instance.
func NewMockIPushClient(ctrl *gomock.Controller) *MockIPushClient {
	mock := &MockIPushClient{ctrl: ctrl}
	mock.recorder = &MockIPushClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPushClient) EXPECT() *MockIPushClientMockRecorder {
	return m.recorder
}

// SendPushNotification mocks base method.
func (m *MockIPushClient) SendPushNotification(ctx context.Context, userID int, title, body string, data map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPushNotification", ctx, userID, title, body, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPushNotification indicates an expected call of SendPushNotification.
func (mr *MockIPushClientMockRecorder) SendPushNotification(ctx, userID, title, body, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushNotification", reflect.TypeOf((*MockIPushClient)(nil).SendPushNotification), ctx, userID, title, body, data)
}
